name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js 18.20.0
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 18.20.0
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npm run lint
